package com.mycompany.maplegood;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jackvanmilligen
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
        //find out which student
        PasswordManager.findStudent();
        
        //set boxes
        
        //set name
        nameLabel.setText(PasswordManager.currentStudent.getFullName());
        
        //set extra curiculars
        extraCuriculars.setText(PasswordManager.currentStudent.getExtras());
        
        //set class names
        class1.setText(PasswordManager.currentStudent.getTimeTable()[0]);
        class2.setText(PasswordManager.currentStudent.getTimeTable()[1]);
        class3.setText(PasswordManager.currentStudent.getTimeTable()[2]);
        class4.setText(PasswordManager.currentStudent.getTimeTable()[3]);
        
        //grade sets
        grade1.setText("" + PasswordManager.currentStudent.getGrade(1));
        grade2.setText("" + PasswordManager.currentStudent.getGrade(2));
        grade3.setText("" + PasswordManager.currentStudent.getGrade(3));
        grade4.setText("" + PasswordManager.currentStudent.getGrade(4));
        
        //set overall average
        avgGrade.setText("" + PasswordManager.currentStudent.getAv());
        
        //find their classes location in the class array
        Class[] classes = new Class[4];
        //iterate through students class
        for(int i = 0; i < PasswordManager.currentStudent.getTimeTable().length; i++){
            
            //iterate through all possible classes
            for(int j = 0; j < PasswordManager.schoolClass.length; j++){
                
                //check if classes line up
                if(PasswordManager.currentStudent.getTimeTable()[i].equals(PasswordManager.schoolClass[j].className())){
                    classes[i] = PasswordManager.schoolClass[j];
                }
            }
        }
        
        //set class averages
        
        per1Label.setText("" + classes[0].getClassAv());
        per2Label.setText("" + classes[1].getClassAv());
        per3Label.setText("" + classes[2].getClassAv());
        per4Label.setText("" + classes[3].getClassAv());
        //set class ranks
        
        rank1Label.setText("" + classes[0].getRank(PasswordManager.currentStudent.getFullName()));
        rank2Label.setText("" + classes[1].getRank(PasswordManager.currentStudent.getFullName()));
        rank3Label.setText("" + classes[2].getRank(PasswordManager.currentStudent.getFullName()));
        rank4Label.setText("" + classes[3].getRank(PasswordManager.currentStudent.getFullName()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        class1 = new javax.swing.JLabel();
        grade1 = new javax.swing.JLabel();
        class2 = new javax.swing.JLabel();
        grade2 = new javax.swing.JLabel();
        class3 = new javax.swing.JLabel();
        grade3 = new javax.swing.JLabel();
        class4 = new javax.swing.JLabel();
        grade4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        avgGrade = new javax.swing.JLabel();
        resetToLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rank1Label = new javax.swing.JLabel();
        rank2Label = new javax.swing.JLabel();
        rank3Label = new javax.swing.JLabel();
        rank4Label = new javax.swing.JLabel();
        per1Label = new javax.swing.JLabel();
        per3Label = new javax.swing.JLabel();
        per2Label = new javax.swing.JLabel();
        per4Label = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        extraCuriculars = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        class1.setText("Class 1");

        grade1.setText("Grade");

        class2.setText("Class 2");

        grade2.setText("Grade");

        class3.setText("Class 3");

        grade3.setText("Grade");

        class4.setText("Class 4");

        grade4.setText("Grade");

        jLabel10.setText("Overall Average:");

        avgGrade.setText("Grade");

        resetToLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        resetToLogin.setText("Return To Login");
        resetToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetToLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Class Average");

        jLabel2.setText("Rank");

        jLabel3.setText("Student Grade");

        rank1Label.setText("Rank 1");

        rank2Label.setText("Rank 2");

        rank3Label.setText("Rank 3");

        rank4Label.setText("Rank 4");

        per1Label.setText("Per 1 Grade");

        per3Label.setText("Per 3 Grade");

        per2Label.setText("Per 2 Grade");

        per4Label.setText("Per 4 Grade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(class3)
                                        .addGap(18, 18, 18)
                                        .addComponent(per3Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rank3Label))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(class1)
                                            .addComponent(class2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(per2Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rank2Label))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(per1Label)
                                                .addGap(49, 49, 49)
                                                .addComponent(rank1Label))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(class4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(avgGrade)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(per4Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rank4Label)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grade1)
                                    .addComponent(grade2)
                                    .addComponent(grade3)
                                    .addComponent(grade4))
                                .addGap(34, 34, 34)))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rank1Label)
                    .addComponent(per1Label)
                    .addComponent(grade1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class2)
                    .addComponent(rank2Label)
                    .addComponent(per2Label)
                    .addComponent(grade2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class3)
                    .addComponent(rank3Label)
                    .addComponent(per3Label)
                    .addComponent(grade3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class4)
                    .addComponent(grade4)
                    .addComponent(rank4Label)
                    .addComponent(per4Label))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(avgGrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(resetToLogin)
                .addGap(19, 19, 19))
        );

        nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nameLabel.setText("Name");

        jLabel12.setText("Extra Curriculars:");

        extraCuriculars.setText("Varsity Football, Track, Science Club");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel14.setText("Time Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extraCuriculars, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(381, 381, 381))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(extraCuriculars)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetToLoginActionPerformed
        this.dispose();
        LaunchPage launch = new LaunchPage();
        launch.setVisible(true);
    }//GEN-LAST:event_resetToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgGrade;
    private javax.swing.JLabel class1;
    private javax.swing.JLabel class2;
    private javax.swing.JLabel class3;
    private javax.swing.JLabel class4;
    private javax.swing.JLabel extraCuriculars;
    private javax.swing.JLabel grade1;
    private javax.swing.JLabel grade2;
    private javax.swing.JLabel grade3;
    private javax.swing.JLabel grade4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel per1Label;
    private javax.swing.JLabel per2Label;
    private javax.swing.JLabel per3Label;
    private javax.swing.JLabel per4Label;
    private javax.swing.JLabel rank1Label;
    private javax.swing.JLabel rank2Label;
    private javax.swing.JLabel rank3Label;
    private javax.swing.JLabel rank4Label;
    private javax.swing.JButton resetToLogin;
    // End of variables declaration//GEN-END:variables

}
