package com.mycompany.maplegood;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jackvanmilligen
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
        //find out which student
        PasswordManager.findStudent();
        
        //set boxes
        
        //set name
        nameLabel.setText(PasswordManager.currentStudent.getFullName());
        
        //set extra curiculars
        extraCuriculars.setText(PasswordManager.currentStudent.getExtras());
        
        //set class names
        class1.setText(PasswordManager.currentStudent.getTimeTable()[0].toUpperCase());
        class2.setText(PasswordManager.currentStudent.getTimeTable()[1].toUpperCase());
        class3.setText(PasswordManager.currentStudent.getTimeTable()[2].toUpperCase());
        class4.setText(PasswordManager.currentStudent.getTimeTable()[3].toUpperCase());
        
        //grade sets
        grade1.setText("" + PasswordManager.currentStudent.getGrade(1));
        grade2.setText("" + PasswordManager.currentStudent.getGrade(2));
        grade3.setText("" + PasswordManager.currentStudent.getGrade(3));
        grade4.setText("" + PasswordManager.currentStudent.getGrade(4));
        
        //set overall average
        avgGrade.setText("" + PasswordManager.currentStudent.getAv());
        
        Class[] classes = PasswordManager.currStudentTimeTable();
        
        per1Label.setText("" + classes[0].getClassAv());
        per2Label.setText("" + classes[1].getClassAv());
        per3Label.setText("" + classes[2].getClassAv());
        per4Label.setText("" + classes[3].getClassAv());
        
//set class ranks
        rank1Label.setText("" + classes[0].getRank(PasswordManager.currentStudent.getFullName()));
        rank2Label.setText("" + classes[1].getRank(PasswordManager.currentStudent.getFullName()));
        rank3Label.setText("" + classes[2].getRank(PasswordManager.currentStudent.getFullName()));
        rank4Label.setText("" + classes[3].getRank(PasswordManager.currentStudent.getFullName()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        class1 = new javax.swing.JLabel();
        grade1 = new javax.swing.JLabel();
        class2 = new javax.swing.JLabel();
        grade2 = new javax.swing.JLabel();
        class3 = new javax.swing.JLabel();
        grade3 = new javax.swing.JLabel();
        class4 = new javax.swing.JLabel();
        grade4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        avgGrade = new javax.swing.JLabel();
        resetToLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rank1Label = new javax.swing.JLabel();
        rank2Label = new javax.swing.JLabel();
        rank3Label = new javax.swing.JLabel();
        rank4Label = new javax.swing.JLabel();
        per1Label = new javax.swing.JLabel();
        per3Label = new javax.swing.JLabel();
        per2Label = new javax.swing.JLabel();
        per4Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        extraCuriculars = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        class1.setText("Class 1");
        jPanel1.add(class1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 25));

        grade1.setText("Grade");
        jPanel1.add(grade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        class2.setText("Class 2");
        jPanel1.add(class2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        grade2.setText("Grade");
        jPanel1.add(grade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        class3.setText("Class 3");
        jPanel1.add(class3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        grade3.setText("Grade");
        jPanel1.add(grade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        class4.setText("Class 4");
        jPanel1.add(class4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        grade4.setText("Grade");
        jPanel1.add(grade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel10.setText("Overall Average:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        avgGrade.setText("Grade");
        jPanel1.add(avgGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        resetToLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        resetToLogin.setText("Return To Login");
        resetToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetToLoginActionPerformed(evt);
            }
        });
        jPanel1.add(resetToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 457, 174, -1));

        jLabel1.setText("Class Average");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setText("Rank");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel3.setText("Student Grade");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        rank1Label.setText("Rank 1");
        jPanel1.add(rank1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        rank2Label.setText("Rank 2");
        jPanel1.add(rank2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        rank3Label.setText("Rank 3");
        jPanel1.add(rank3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        rank4Label.setText("Rank 4");
        jPanel1.add(rank4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        per1Label.setText("Per 1 Grade");
        jPanel1.add(per1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        per3Label.setText("Per 3 Grade");
        jPanel1.add(per3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        per2Label.setText("Per 2 Grade");
        jPanel1.add(per2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        per4Label.setText("Per 4 Grade");
        jPanel1.add(per4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jSeparator1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, 10));

        jSeparator2.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 710, 10));

        jSeparator3.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 10));

        jSeparator4.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 710, 10));

        jSeparator5.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 710, 10));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nameLabel.setText("Name");

        jLabel12.setText("Extra Curriculars:");

        extraCuriculars.setText("Varsity Football, Track, Science Club");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel14.setText("Time Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extraCuriculars, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(659, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(381, 381, 381))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(extraCuriculars)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetToLoginActionPerformed
        this.dispose();
        LaunchPage launch = new LaunchPage();
        launch.setVisible(true);
    }//GEN-LAST:event_resetToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgGrade;
    private javax.swing.JLabel class1;
    private javax.swing.JLabel class2;
    private javax.swing.JLabel class3;
    private javax.swing.JLabel class4;
    private javax.swing.JLabel extraCuriculars;
    private javax.swing.JLabel grade1;
    private javax.swing.JLabel grade2;
    private javax.swing.JLabel grade3;
    private javax.swing.JLabel grade4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel per1Label;
    private javax.swing.JLabel per2Label;
    private javax.swing.JLabel per3Label;
    private javax.swing.JLabel per4Label;
    private javax.swing.JLabel rank1Label;
    private javax.swing.JLabel rank2Label;
    private javax.swing.JLabel rank3Label;
    private javax.swing.JLabel rank4Label;
    private javax.swing.JButton resetToLogin;
    // End of variables declaration//GEN-END:variables

}
